Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,7 +23,20 @@ jobs:
           eval $(ssh-agent -s)
 
           # Add the private key to the SSH agent
-          echo "$NEW_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+          # echo "$NEW_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+
+          # Save the SSH key to a temporary file
+          echo "$NEW_SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/ssh_key
+          chmod 600 /tmp/ssh_key
+          
+          # Add the SSH key to the agent
+          if ! ssh-add /tmp/ssh_key; then
+            echo "Failed to add SSH key"
+            exit 1
+          fi
+          
+          # Clean up the temporary key file
+          rm /tmp/ssh_key
 
           # Connect to the server and execute commands
           ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
