Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,8 +23,11 @@ jobs:
           eval $(ssh-agent -s)
 
           # Add the private key to the SSH agent
-          echo "$NEW_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-
+          if ! echo "$NEW_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -; then
+            echo "Failed to add SSH key. Check the key format."
+            exit 1
+          fi
+          
           # Connect to the server and execute commands
           ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
             cd ~/online_payment_api_fastApi
